//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSViewUIExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSViewUIExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to google.charts.load(&apos;current&apos;, {&apos;packages&apos;:[&apos;corechart&apos;]});
        ///google.charts.load(&apos;current&apos;, {&apos;packages&apos;:[&apos;treemap&apos;]});
        ///
        ///google.charts.setOnLoadCallback(OnLoad);
        ///
        ///window.onresize = RefreshSelectedView;
        ///
        ///// General data and functions -------------------------------------------------------------
        ///var allColors = 
        ///[
        ///    &apos;#3366cc&apos;,
        ///    &apos;#dc3912&apos;,
        ///    &apos;#ff9900&apos;,
        ///    &apos;#109618&apos;,
        ///    &apos;#990099&apos;,
        ///    &apos;#0099c6&apos;,
        ///    &apos;#dd4477&apos;,
        ///    &apos;#66aa00&apos;,
        ///    &apos;#b82e2e&apos;,
        ///    &apos;#316395&apos;,
        ///    &apos;#994499&apos;,
        ///    &apos;#22aa99&apos;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSViewDefaultCode {
            get {
                return ResourceManager.GetString("JSViewDefaultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Copyright (c) Andrew J. Peterson, NDP Software
        ///
        ///var ColorHelper;
        ///
        ///(function () {
        ///
        ///  function isArray(object) {
        ///    return typeof object === &apos;object&apos; &amp;&amp;
        ///        Object.prototype.toString.call(object) === &apos;[object Array]&apos;;
        ///  }
        ///
        ///
        ///  /*
        ///   Use a singleton cache of all color strings we see.
        ///   Each key points to a structure, which can have hex, rgb, etc. values in it.
        ///   */
        ///  var immutableCache = {};
        ///
        ///  // returns (or creates) the cached color structure
        ///  var colorCache = function (c) {
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSViewDefaultColorUtil {
            get {
                return ResourceManager.GetString("JSViewDefaultColorUtil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///    
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;https://www.gstatic.com/charts/loader.js&quot;&gt;&lt;/script&gt;
        ///
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;{{{JSVIEW_USERDATA}}}&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;{{{JSVIEW_USERCODE}}}&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;{{{JSVIEW_COLORUTIL}}}&quot;&gt;&lt;/script&gt;
        ///        
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSViewDefaultPage {
            get {
                return ResourceManager.GetString("JSViewDefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  
        ///*
        ///{
        ///	font-family: Tahoma;
        ///	font-size: 9pt;
        ///}
        /// 
        ///body
        ///{
        ///	margin: 0px;
        ///	padding: 0px;
        ///	border: none;
        ///}
        ///
        ///.content
        ///{
        ///	border: 1px solid gray; 
        ///	background: white; 
        ///	height: 100%;
        ///	width: 99%; /* prevent horz scrollbar */
        ///	margin: 3px 0px 0px 0px;
        ///}
        ///
        ///.
        /// </summary>
        internal static string JSViewDefaultStyles {
            get {
                return ResourceManager.GetString("JSViewDefaultStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolbar_std {
            get {
                object obj = ResourceManager.GetObject("toolbar_std", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WordCloud {
            get {
                object obj = ResourceManager.GetObject("WordCloud", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
