//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JSViewUIExtension.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JSViewUIExtension.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to google.charts.load(&apos;current&apos;, {&apos;packages&apos;:[&apos;corechart&apos;]});
        ///google.charts.load(&apos;current&apos;, {&apos;packages&apos;:[&apos;treemap&apos;]});
        ///
        ///google.charts.setOnLoadCallback(OnLoad);
        ///
        ///// General data and functions -------------------------------------------------------------
        ///var allColors = 
        ///[
        ///    &apos;#3366cc&apos;,
        ///    &apos;#dc3912&apos;,
        ///    &apos;#ff9900&apos;,
        ///    &apos;#109618&apos;,
        ///    &apos;#990099&apos;,
        ///    &apos;#0099c6&apos;,
        ///    &apos;#dd4477&apos;,
        ///    &apos;#66aa00&apos;,
        ///    &apos;#b82e2e&apos;,
        ///    &apos;#316395&apos;,
        ///    &apos;#994499&apos;,
        ///    &apos;#22aa99&apos;,
        ///    &apos;#aaaa11&apos;,
        ///    &apos;#6633cc&apos;,
        ///    &apos;#e673 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSViewDefaultCode {
            get {
                return ResourceManager.GetString("JSViewDefaultCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;style&gt;
        ///            body { font-family: Tahoma; font-size: small }
        ///        &lt;/style&gt;
        ///    
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;https://www.gstatic.com/charts/loader.js&quot;&gt;&lt;/script&gt;
        ///
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;{{{JSVIEW_USERDATA}}}&quot;&gt;&lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot; src=&quot;{{{JSVIEW_USERCODE}}}&quot;&gt;&lt;/script&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JSViewDefaultPage {
            get {
                return ResourceManager.GetString("JSViewDefaultPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string JSViewDefaultStyles {
            get {
                return ResourceManager.GetString("JSViewDefaultStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolbar_std {
            get {
                object obj = ResourceManager.GetObject("toolbar_std", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon WordCloud {
            get {
                object obj = ResourceManager.GetObject("WordCloud", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
