//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by GanttChartExt.rc
//
#define IDD_GANTTTREE_DIALOG            103
#define IDB_TOOLBAR_STD                 245
#define IDI_HELP_BUTTON                 293
#define IDR_GANTTCHART                  1000
#define IDC_TREEHEADER                  1004
#define IDC_GANTTLIST                   1005
#define IDC_GANTTTREE                   1006
#define IDC_DISPLAY                     1015
#define IDC_DISPLAYALLOCTO              1016
#define IDC_DISPLAYTASKTITLE            1017
#define IDC_GOTOTODAY                   1020
#define IDC_SELECTEDTASKDATES           1032
#define IDC_DRAGMODE                    1033
#define IDC_SNAPMODES                   1034
#define IDC_SETWEEKENDCOLOR             1072
#define IDC_SETTODAYCOLOR               1073
#define IDC_SETPARENTCOLOR              1074
#define IDC_SETDEFAULTCOLOR             1075
#define IDC_SETNONWORKINGHOURSCOLOR     1076
#define IDS_GANTT_DAYS                  2001
#define IDS_GANTT_WEEKS                 2002
#define IDS_SNAP_FREE                   2003
#define IDS_SNAP_NEARESTDAY             2004
#define IDS_SNAP_NEARESTHALFDAY         2005
#define IDS_SNAP_NEARESTHALFYEAR        2006
#define IDS_SNAP_NEARESTHOUR            2007
#define IDS_SNAP_NEARESTMONTH           2008
#define IDS_SNAP_NEARESTQUARTER         2009
#define IDS_SNAP_NEARESTWEEK            2010
#define IDS_SNAP_NEARESTYEAR            2011
#define IDS_DISPLAYDAYSHOURS            2012
#define IDC_DIVIDER                     16001
#define IDC_AUTOSCROLLSELECTION         16002
#define IDD_PREFERENCES_DIALOG          16002
#define IDC_PREFERENCES                 16003
#define IDD_PREFERENCES_PAGE            16003
#define IDC_WEEKENDCOLOR                16004
#define IDC_TODAYCOLOR                  16005
#define IDR_TOOLBAR                     16006
#define IDC_DEFAULTCOLOR                16006
#define IDC_DATESGROUP                  16007
#define IDC_COLORSGROUP                 16008
#define IDD_CREATEDEPENDS_DIALOG        16008
#define IDC_NONWORKINGHOURSCOLOR        16009
#define IDB_CHECKBOXES                  16010
#define IDC_CALCULATEMISSINGSTARTDATE   16012
#define IDC_CALCULATEMISSINGDUEDATE     16013
#define IDC_CALCULATEPARENTDATES        16014
#define IDC_DEFAULTPARENTCOLORS         16015
#define IDC_NOPARENTCOLOR               16016
#define IDC_SPECIFYPARENTCOLOR          16017
#define IDC_SHOWALLOCTOCOLUMN           16018
#define IDC_PPHOST                      16019
#define IDC_USETAGFORMILESTONE          16020
#define IDC_MILESTONETAG                16021
#define IDC_DISPLAYPROGRESS             16022
#define IDC_TB_PLACEHOLDER              16024
#define IDC_CURRENTSTAGE                16025
#define IDC_WORKLOAD_FRAME              16025
#define IDC_GANTTCHART_FRAME            16025
#define IDC_DISPLAY_LABEL               16026
#define IDC_SNAPMODES_LABEL             16027
#define IDC_SELECTEDTASKDATES_LABEL     16028
#define IDC_ACTIVEDATERANGE_LABEL       16028
#define IDC_DECADESAREONEBASED          16029
#define IDC_COLUMNVISIBILITY            16032
#define IDC_DISPLAYPARENTSASROLLUPS     16033
#define IDC_ACTIVEDATERANGE             16034
#define ID_GANTT_GOTOTODAY              32774
#define ID_GANTT_PREFS                  32775
#define ID_GANTT_NEWDEPENDS             32776
#define IDS_PICKINGFROMTASK             32777
#define IDS_PICKINGTOTASKADD            32778
#define ID_GANTT_EDITDEPENDS            32779
#define ID_GANTT_DELETEDEPENDS          32780
#define IDS_PICKINGFROMDEPEND_EDIT      32781
#define IDS_PICKINGFROMDEPEND_DELETE    32782
#define IDS_PICKINGTOTASKEDIT           32783
#define IDS_PICKED                      32786
#define IDS_CREATEDEPEND_TITLE          32787
#define IDS_EDITDEPEND_TITLE            32788
#define IDS_DELETEDEPEND_TITLE          32789
#define IDS_DISPLAYYEARS                32790
#define IDS_DISPLAYQUARTERSSHORT        32791
#define IDS_DISPLAYQUARTERSMID          32792
#define IDS_DISPLAYQUARTERSLONG         32793
#define IDS_DISPLAYMONTHSSHORT          32794
#define IDS_DISPLAYMONTHSMID            32795
#define IDS_DISPLAYMONTHSLONG           32796
#define IDS_DISPLAYWEEKSSHORT           32797
#define IDS_DISPLAYWEEKSMID             32798
#define IDS_DISPLAYWEEKSLONG            32799
#define IDS_DISPLAYDAYSSHORT            32800
#define IDS_DISPLAYDAYSMID              32801
#define IDS_DISPLAYDAYSLONG             32802
#define IDS_DISPLAYQUARTERCENTURIES     57671
#define IDS_DISPLAYDECADES              57672
#define IDS_SNAP_NEARESTQUARTERCENTURY  57673
#define IDS_SNAP_NEARESTDECADE          57674
#define IDS_SNAP_NEARESTHALFHOUR        57675
#define IDS_COL_STARTDATE               57676
#define IDS_COL_DUEDATE                 57677
#define IDS_COL_ALLOCTO                 57678
#define IDS_COL_PERCENTDONE             57679
#define IDS_COL_TASKID                  57680
#define IDS_ATTRIB_STARTDATE            57681
#define IDS_ATTRIB_DUEDATE              57682
#define IDS_ATTRIB_ALLOCTO              57683
#define IDS_ATTRIB_PERCENTDONE          57684
#define IDS_ATTRIB_TASKID               57685
#define IDS_ATTRIB_DONEDATE             57686
#define IDS_COL_DONEDATE                57687
#define IDS_ACTIVEDATERANGE             57688
#define IDS_DISPLAYHINT                 57689

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        16011
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         16035
#define _APS_NEXT_SYMED_VALUE           16000
#endif
#endif
