
#ifndef KANBANCOLORS_H
#define KANBANCOLORS_H

#include "..\3rdparty\xnamedcolors.h"

COLORREF KBCOLORS[] = 
{
// 	colorAliceBlue,            
// 	colorAntiqueWhite,         
// 	colorAqua,                 
// 	colorAquamarine,          
//	colorAzure,                
// 	colorBeige,                
// 	colorBisque,               
//	colorBlack,                
//	colorBlanchedAlmond,       
	colorBlue,                 
	colorBlueViolet,           
	colorBrown,                
	colorBurlywood,            
	colorCadetBlue,            
//	colorChartreuse,           
	colorChocolate,            
	colorCoral,                
	colorCornflowerBlue,       
//	colorCornsilk,             
	colorCrimson,              
//	colorCyan,                 
// 	colorDarkBlue,             
// 	colorDarkCyan,             
// 	colorDarkGoldenRod,        
// 	colorDarkGray,             
// 	colorDarkGreen,            
// 	colorDarkKhaki,            
// 	colorDarkMagenta,          
// 	colorDarkOliveGreen,       
// 	colorDarkOrange,           
// 	colorDarkOrchid,           
// 	colorDarkRed,              
// 	colorDarkSalmon,           
// 	colorDarkSeaGreen,         
// 	colorDarkSlateBlue,        
// 	colorDarkSlateGray,        
// 	colorDarkTurquoise,        
// 	colorDarkViolet,           
	colorDeepPink,             
	colorDeepSkyBlue,          
	colorDimGray,              
	colorDodgerBlue,           
	colorFireBrick,            
//	colorFloralWhite,          
	colorForestGreen,          
	colorFuchsia,              
// 	colorGainsboro,            
// 	colorGhostWhite,           
	colorGold,                 
	colorGoldenRod,            
	colorGray,                 
	colorGreen,                
// 	colorGreenYellow,          
// 	colorHoneyDew,             
	colorHotPink,              
	colorIndianRed,            
	colorIndigo,               
// 	colorIvory,                
// 	colorKhaki,                
// 	colorLavender,             
//	colorLavenderBlush,        
	colorLawngreen,            
// 	colorLemonChiffon,         
// 	colorLightBlue,            
// 	colorLightCoral,           
// 	colorLightCyan,            
// 	colorLightGoldenRodYellow, 
// 	colorLightGreen,           
// 	colorLightGrey,            
// 	colorLightPink,            
// 	colorLightSalmon,          
// 	colorLightSeaGreen,        
// 	colorLightSkyBlue,         
// 	colorLightSlateGray,       
// 	colorLightSteelBlue,       
// 	colorLightYellow,          
//	colorLime,                 
	colorLimeGreen,            
//	colorLinen,                
//	colorMagenta,              
	colorMaroon,               
	colorMediumAquamarine,     
	colorMediumBlue,           
	colorMediumOrchid,         
	colorMediumPurple,         
	colorMediumSeaGreen,       
	colorMediumSlateBlue,      
	colorMediumSpringGreen,    
	colorMediumTurquoise,      
	colorMediumVioletRed,      
	colorMidnightBlue,         
// 	colorMintCream,            
// 	colorMistyRose,            
// 	colorMoccasin,             
// 	colorNavajoWhite,          
//	colorNavy,                 
//	colorOldLace,              
//	colorOlive,                
	colorOliveDrab,            
	colorOrange,               
	colorOrangeRed,            
	colorOrchid,               
// 	colorPaleGoldenRod,        
// 	colorPaleGreen,            
// 	colorPaleTurquoise,        
// 	colorPaleVioletRed,        
// 	colorPapayaWhip,           
// 	colorPeachPuff,            
	colorPeru,                 
// 	colorPink,                 
// 	colorPlum,                 
// 	colorPowderBlue,           
	colorPurple,               
	colorRed,                  
	colorRosyBrown,            
	colorRoyalBlue,            
	colorSaddleBrown,          
	colorSalmon,               
	colorSandyBrown,           
	colorSeaGreen,             
//	colorSeaShell,             
	colorSienna,               
//	colorSilver,               
	colorSkyBlue,              
	colorSlateBlue,            
	colorSlateGray,            
// 	colorSnow,                 
// 	colorSpringGreen,          
	colorSteelBlue,            
//	colorTan,                  
//	colorTeal,                 
//	colorThistle,              
	colorTomato,               
//	colorTurquoise,            
	colorViolet,               
// 	colorWheat,                
// 	colorWhite,                
// 	colorWhiteSmoke,           
// 	colorYellow,               
	colorYellowGreen          
};
const UINT NUM_KBCOLORS = (sizeof(KBCOLORS) / sizeof(COLORREF));

#endif //XNAMEDCOLORS_H
