// OutlookHelperEnum.h: enums for the COutlookHelper class.
//
//////////////////////////////////////////////////////////////////////

#if !defined(AFX_OUTLOOKHELPERENUM_H__C57DEEC1_2B2B_490A_9F2B_1A7B9127313F__INCLUDED_)
#define AFX_OUTLOOKHELPERENUM_H__C57DEEC1_2B2B_490A_9F2B_1A7B9127313F__INCLUDED_

#if _MSC_VER > 1000
#pragma once
#endif // _MSC_VER > 1000

enum OUTLOOK_FIELDTYPE
{
	// DO NOT CHANGE THE ORDER OF EXISTING ITEMS

	// Common ----------------------------
	OA_BODY = 0,
	OA_BILLINGINFORMATION,
	OA_CATEGORIES,
	OA_COMPANIES,
	OA_CONVERSATIONTOPIC,
	OA_CREATIONTIME,
	OA_ENTRYID,
	OA_IMPORTANCE,
	OA_LASTMODIFICATIONTIME,
	OA_MESSAGECLASS,
	OA_MILEAGE,
	OA_SENSITIVITY,
	OA_TITLE,

	// Mail specific ---------------------
	OA_BCC = 100,
	OA_CC,
	OA_EXPIRYTIME,
	OA_FLAGREQUEST,
	OA_PERMISSION,
	OA_RECEIVEDBYNAME,
	OA_RECEIVEDTIME,
	OA_REMINDERTIME,
	OA_REPLYRECIPIENTNAMES,
	OA_SENDEREMAILADDRESS,
	OA_SENDERNAME,
	OA_SENTON,
	OA_SENTONBEHALFOFNAME,
	OA_TASKCOMPLETEDDATE,
	OA_TASKDUEDATE,
	OA_TASKSTARTDATE,
	OA_TO,
	
	// Task specific ---------------------
	OA_ACTUALWORK = 200,
	OA_COMPLETE,
	OA_DATECOMPLETED,
	OA_DELEGATOR,
	OA_DUEDATE,
	OA_ISRECURRING,
	OA_OWNER,
	OA_PERCENTCOMPLETE,
	OA_SCHEDULEPLUSPRIORITY,
	OA_STARTDATE,
	OA_STATUS,
	OA_TEAMTASK,
	OA_TOTALWORK,

	// Appointment specific --------------
	OA_DURATION = 300,
	OA_END,
	OA_START,
	// TODO


	// Journal specific ------------------
	// TODO


	// Note specific ---------------------
	// TODO


	// Contact specific ------------------
	// TODO
};


enum // FormatItemAsUrl
{
	OAFMT_NICE				= 0x01,
	OAFMT_BRACED			= 0x02,
	OAFMT_REPLACESPACES		= 0x04,
};

enum // Folder Class
{
	OFC_DELETEDITEMS		= 3,
	OFC_OUTBOX				= 4,
	OFC_SENTMAIL			= 5,
	OFC_INBOX				= 6,
	OFC_CALENDAR			= 9,
	OFC_CONTACTS			= 10,
	OFC_JOURNAL				= 11,
	OFC_NOTES				= 12,
	OFC_TASKS				= 13,
};

enum // Object Class
{
	OOC_ITEM					= -1,
	OOC_APPLICATION				= 0,
	OOC_NAMESPACE				= 1,
	OOC_FOLDER					= 2,
	OOC_RECIPIENT				= 4,
	OOC_ATTACHMENT				= 5,
	OOC_ADDRESSLIST				= 7,
	OOC_ADDRESSENTRY			= 8,
	OOC_FOLDERS					= 15,
	OOC_ITEMS					= 16,
	OOC_RECIPIENTS				= 17,
	OOC_ATTACHMENTS				= 18,
	OOC_ADDRESSLISTS			= 20,
	OOC_ADDRESSENTRIES			= 21,
	OOC_APPOINTMENT				= 26,
	OOC_RECURRENCEPATTERN		= 28,
	OOC_EXCEPTIONS				= 29,
	OOC_EXCEPTION				= 30,
	OOC_ACTION					= 32,
	OOC_ACTIONS					= 33,
	OOC_EXPLORER				= 34,
	OOC_INSPECTOR				= 35,
	OOC_PAGES					= 36,
	OOC_FORMDESCRIPTION			= 37,
	OOC_USERPROPERTIES			= 38,
	OOC_USERPROPERTY			= 39,
	OOC_CONTACT					= 40,
	OOC_DOCUMENT				= 41,
	OOC_JOURNAL					= 42,
	OOC_MAIL					= 43,
	OOC_NOTE					= 44,
	OOC_POST					= 45,
	OOC_REPORT					= 46,
	OOC_REMOTE					= 47,
	OOC_TASK					= 48,
	OOC_TASKREQUEST				= 49,
	OOC_TASKREQUESTUPDATE		= 50,
	OOC_TASKREQUESTACCEPT		= 51,
	OOC_TASKREQUESTDECLINE		= 52,
	OOC_MEETINGREQUEST			= 53,
	OOC_MEETINGCANCELLATION		= 54,
	OOC_MEETINGRESPONSENEGATIVE = 55,
	OOC_MEETINGRESPONSEPOSITIVE = 56,
	OOC_MEETINGRESPONSETENTATIVE = 57,
	OOC_EXPLORERS				= 60,
	OOC_INSPECTORS				= 61,
	OOC_PANES					= 62,
	OOC_OUTLOOKBARPANE			= 63,
	OOC_OUTLOOKBARSTORAGE		= 64,
	OOC_OUTLOOKBARGROUPS		= 65,
	OOC_OUTLOOKBARGROUP			= 66,
	OOC_OUTLOOKBARSHORTCUTS		= 67,
	OOC_OUTLOOKBARSHORTCUT		= 68,
	OOC_DISTRIBUTIONLIST		= 69,
	OOC_PROPERTYPAGESITE		= 70,
	OOC_PROPERTYPAGES			= 71,
	OOC_SYNCOBJECT				= 72,
	OOC_SYNCOBJECTS				= 73,
	OOC_SELECTION				= 74,
	OOC_LINK					= 75,
	OOC_LINKS					= 76,
	OOC_SEARCH					= 77,
	OOC_RESULTS					= 78,
	OOC_VIEWS					= 79,
	OOC_VIEW					= 80,
	OOC_ITEMPROPERTIES			= 98,
	OOC_ITEMPROPERTY			= 99,
	OOC_REMINDERS				= 100,
	OOC_REMINDER				= 101,
	OOC_CONFLICT				= 102,
	OOC_CONFLICTS				= 103,
	OOC_SHARING					= 104,
	OOC_ACCOUNT					= 105,
	OOC_ACCOUNTS				= 106,
	OOC_STORE					= 107,
	OOC_STORES					= 108,
	OOC_SELECTNAMESDIALOG		= 109,
	OOC_EXCHANGEUSER			= 110,
	OOC_EXCHANGEDISTRIBUTIONLIST = 111,
	OOC_PROPERTYACCESSOR		= 112,
	OOC_STORAGEITEM				= 113,
	OOC_RULES					= 114,
	OOC_RULE					= 115,
	OOC_RULEACTIONS				= 116,
	OOC_RULEACTION				= 117,
	OOC_MOVEORCOPYRULEACTION	= 118,
	OOC_SENDRULEACTION			= 119,
	OOC_TABLE					= 120,
	OOC_ROW						= 121,
	OOC_ASSIGNTOCATEGORYRULEACTION = 122,
	OOC_PLAYSOUNDRULEACTION		= 123,
	OOC_MARKASTASKRULEACTION	= 124,
	OOC_NEWITEMALERTRULEACTION	= 125,
	OOC_RULECONDITIONS			= 126,
	OOC_RULECONDITION			= 127,
	OOC_IMPORTANCERULECONDITION = 128,
	OOC_FORMREGION				= 129,
	OOC_CATEGORYRULECONDITION	= 130,
	OOC_FORMNAMERULECONDITION	= 131,
	OOC_FROMRULECONDITION		= 132,
	OOC_SENDERINADDRESSLISTRULECONDITION = 133,
	OOC_TEXTRULECONDITION		= 134,
	OOC_ACCOUNTRULECONDITION	= 135,
	OOC_CLASSTABLEVIEW			= 136,
	OOC_CLASSICONVIEW			= 137,
	OOC_CLASSCARDVIEW			= 138,
	OOC_CLASSCALENDARVIEW		= 139,
	OOC_CLASSTIMELINEVIEW		= 140,
	OOC_VIEWFIELDS				= 141,
	OOC_VIEWFIELD				= 142,
	OOC_ORDERFIELD				= 144,
	OOC_ORDERFIELDS				= 145,
	OOC_VIEWFONT				= 146,
	OOC_AUTOFORMATRULE			= 147,
	OOC_AUTOFORMATRULES			= 148,
	OOC_COLUMNFORMAT			= 149,
	OOC_COLUMNS					= 150,
	OOC_CALENDARSHARING			= 151,
	OOC_CATEGORY				= 152,
	OOC_CATEGORIES				= 153,
	OOC_COLUMN					= 154,
	OOC_CLASSNAVIGATIONPANE		= 155,
	OOC_NAVIGATIONMODULES		= 156,
	OOC_NAVIGATIONMODULE		= 157,
	OOC_MAILMODULE				= 158,
	OOC_CALENDARMODULE			= 159,
	OOC_CONTACTSMODULE			= 160,
	OOC_TASKSMODULE				= 161,
	OOC_JOURNALMODULE			= 162,
	OOC_NOTESMODULE				= 163,
	OOC_NAVIGATIONGROUPS		= 164,
	OOC_NAVIGATIONGROUP			= 165,
	OOC_NAVIGATIONFOLDERS		= 166,
	OOC_NAVIGATIONFOLDER		= 167,
	OOC_CLASSBUSINESSCARDVIEW	= 168,
	OOC_ATTACHMENTSELECTION		= 169,
	OOC_ADDRESSRULECONDITION	= 170,
	OOC_USERDEFINEDPROPERTY		= 171,
	OOC_USERDEFINEDPROPERTIES	= 172,
	OOC_FROMRSSFEEDRULECONDITION = 173,
	OOC_CLASSTIMEZONE			= 174,
	OOC_CLASSTIMEZONES			= 175,
	OOC_MOBILE					= 176,
	OOC_SOLUTIONSMODULE			= 177,
	OOC_CONVERSATION			= 178,
	OOC_SIMPLEITEMS				= 179,
	OOC_OUTSPACE				= 180,
	OOC_MEETINGFORWARDNOTIFICATION = 181,
	OOC_CONVERSATIONHEADER		= 182,
};

#endif // !defined(AFX_OUTLOOKHELPERENUM_H__C57DEEC1_2B2B_490A_9F2B_1A7B9127313F__INCLUDED_)
