; Listing generated by Microsoft (R) Optimizing Compiler Version 16.00.40219.01 

	TITLE	D:\_code\RTFContentCtrl\InsertTableDlg.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

_DATA	SEGMENT
_THIS_FILE DB	'InsertTableDlg.cpp', 00H
_DATA	ENDS
CONST	SEGMENT
$SG171208 DB	'W', 00H, 'M', 00H, '_', 00H, 'I', 00H, 'C', 00H, 'C', 00H
	DB	'_', 00H, 'W', 00H, 'A', 00H, 'N', 00H, 'T', 00H, 'S', 00H, 'P'
	DB	00H, 'E', 00H, 'L', 00H, 'L', 00H, 'C', 00H, 'H', 00H, 'E', 00H
	DB	'C', 00H, 'K', 00H, 00H, 00H
$SG171213 DB	'W', 00H, 'M', 00H, '_', 00H, 'I', 00H, 'C', 00H, 'C', 00H
	DB	'_', 00H, 'C', 00H, 'O', 00H, 'M', 00H, 'M', 00H, 'E', 00H, 'N'
	DB	00H, 'T', 00H, 'S', 00H, 'C', 00H, 'H', 00H, 'A', 00H, 'N', 00H
	DB	'G', 00H, 'E', 00H, 00H, 00H
$SG171218 DB	'W', 00H, 'M', 00H, '_', 00H, 'I', 00H, 'C', 00H, 'C', 00H
	DB	'_', 00H, 'C', 00H, 'O', 00H, 'M', 00H, 'M', 00H, 'E', 00H, 'N'
	DB	00H, 'T', 00H, 'S', 00H, 'K', 00H, 'I', 00H, 'L', 00H, 'L', 00H
	DB	'F', 00H, 'O', 00H, 'C', 00H, 'U', 00H, 'S', 00H, 00H, 00H
	ORG $+2
$SG171240 DB	'CreateContentInterface', 00H
	ORG $+1
$SG171245 DB	'GetInterfaceVersion', 00H
$SG171258 DB	'CreateContentInterface', 00H
	ORG $+1
$SG171336 DB	'8', 00H, '4', 00H, '9', 00H, 'C', 00H, 'F', 00H, '9', 00H
	DB	'8', 00H, '8', 00H, '-', 00H, '7', 00H, '9', 00H, 'F', 00H, 'E'
	DB	00H, '-', 00H, '4', 00H, '1', 00H, '8', 00H, 'A', 00H, '-', 00H
	DB	'A', 00H, '4', 00H, '0', 00H, 'D', 00H, '-', 00H, '0', 00H, '1'
	DB	00H, 'F', 00H, 'E', 00H, '3', 00H, 'A', 00H, 'F', 00H, 'C', 00H
	DB	'A', 00H, 'B', 00H, '2', 00H, 'C', 00H, 00H, 00H
	ORG $+2
_RTF_TYPEID DD	FLAT:$SG171336
$SG171449 DB	'%', 00H, 'd', 00H, 00H, 00H
	ORG $+2
$SG171450 DB	'%', 00H, 'd', 00H, 00H, 00H
	ORG $+2
$SG171451 DB	'%', 00H, 'd', 00H, 00H, 00H
CONST	ENDS
PUBLIC	??_7CInsertTableDlg@@6B@			; CInsertTableDlg::`vftable'
PUBLIC	??0CInsertTableDlg@@QAE@PAVCWnd@@@Z		; CInsertTableDlg::CInsertTableDlg
PUBLIC	??_R4CInsertTableDlg@@6B@			; CInsertTableDlg::`RTTI Complete Object Locator'
PUBLIC	??_R0?AVCInsertTableDlg@@@8			; CInsertTableDlg `RTTI Type Descriptor'
PUBLIC	??_R3CInsertTableDlg@@8				; CInsertTableDlg::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CInsertTableDlg@@8				; CInsertTableDlg::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CInsertTableDlg@@8		; CInsertTableDlg::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R1A@?0A@EA@CDialog@@8			; CDialog::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCDialog@@@8				; CDialog `RTTI Type Descriptor'
PUBLIC	??_R3CDialog@@8					; CDialog::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CDialog@@8					; CDialog::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CWnd@@8				; CWnd::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCWnd@@@8				; CWnd `RTTI Type Descriptor'
PUBLIC	??_R3CWnd@@8					; CWnd::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CWnd@@8					; CWnd::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CCmdTarget@@8			; CCmdTarget::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCCmdTarget@@@8				; CCmdTarget `RTTI Type Descriptor'
PUBLIC	??_R3CCmdTarget@@8				; CCmdTarget::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CCmdTarget@@8				; CCmdTarget::`RTTI Base Class Array'
PUBLIC	??_R1A@?0A@EA@CObject@@8			; CObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
PUBLIC	??_R0?AVCObject@@@8				; CObject `RTTI Type Descriptor'
PUBLIC	??_R3CObject@@8					; CObject::`RTTI Class Hierarchy Descriptor'
PUBLIC	??_R2CObject@@8					; CObject::`RTTI Base Class Array'
PUBLIC	?GetMessageMap@CInsertTableDlg@@MBEPBUAFX_MSGMAP@@XZ ; CInsertTableDlg::GetMessageMap
PUBLIC	?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z ; CInsertTableDlg::DoDataExchange
PUBLIC	?OnInitDialog@CInsertTableDlg@@MAEHXZ		; CInsertTableDlg::OnInitDialog
EXTRN	??1CComboBox@@UAE@XZ:PROC			; CComboBox::~CComboBox
EXTRN	??1CDialog@@UAE@XZ:PROC				; CDialog::~CDialog
EXTRN	??0CComboBox@@QAE@XZ:PROC			; CComboBox::CComboBox
EXTRN	??0CDialog@@QAE@IPAVCWnd@@@Z:PROC		; CDialog::CDialog
EXTRN	___security_cookie:DWORD
EXTRN	___CxxFrameHandler3:PROC
EXTRN	@__security_check_cookie@4:PROC
EXTRN	__RTC_CheckEsp:PROC
EXTRN	__RTC_Shutdown:PROC
EXTRN	__RTC_InitBase:PROC
EXTRN	??_7type_info@@6B@:QWORD			; type_info::`vftable'
EXTRN	?GetRuntimeClass@CDialog@@UBEPAUCRuntimeClass@@XZ:PROC ; CDialog::GetRuntimeClass
EXTRN	??_ECInsertTableDlg@@UAEPAXI@Z:PROC		; CInsertTableDlg::`vector deleting destructor'
EXTRN	?Serialize@CObject@@UAEXAAVCArchive@@@Z:PROC	; CObject::Serialize
EXTRN	?AssertValid@CDialog@@UBEXXZ:PROC		; CDialog::AssertValid
EXTRN	?Dump@CDialog@@UBEXAAVCDumpContext@@@Z:PROC	; CDialog::Dump
EXTRN	?OnCmdMsg@CDialog@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z:PROC ; CDialog::OnCmdMsg
EXTRN	?OnFinalRelease@CWnd@@UAEXXZ:PROC		; CWnd::OnFinalRelease
EXTRN	?IsInvokeAllowed@CCmdTarget@@UAEHJ@Z:PROC	; CCmdTarget::IsInvokeAllowed
EXTRN	?GetDispatchIID@CCmdTarget@@UAEHPAU_GUID@@@Z:PROC ; CCmdTarget::GetDispatchIID
EXTRN	?GetTypeInfoCount@CCmdTarget@@UAEIXZ:PROC	; CCmdTarget::GetTypeInfoCount
EXTRN	?GetTypeLibCache@CCmdTarget@@UAEPAVCTypeLibCache@@XZ:PROC ; CCmdTarget::GetTypeLibCache
EXTRN	?GetTypeLib@CCmdTarget@@UAEJKPAPAUITypeLib@@@Z:PROC ; CCmdTarget::GetTypeLib
EXTRN	?GetCommandMap@CCmdTarget@@MBEPBUAFX_OLECMDMAP@@XZ:PROC ; CCmdTarget::GetCommandMap
EXTRN	?GetDispatchMap@CCmdTarget@@MBEPBUAFX_DISPMAP@@XZ:PROC ; CCmdTarget::GetDispatchMap
EXTRN	?GetConnectionMap@CCmdTarget@@MBEPBUAFX_CONNECTIONMAP@@XZ:PROC ; CCmdTarget::GetConnectionMap
EXTRN	?GetInterfaceMap@CWnd@@MBEPBUAFX_INTERFACEMAP@@XZ:PROC ; CWnd::GetInterfaceMap
EXTRN	?GetEventSinkMap@CCmdTarget@@MBEPBUAFX_EVENTSINKMAP@@XZ:PROC ; CCmdTarget::GetEventSinkMap
EXTRN	?OnCreateAggregates@CCmdTarget@@UAEHXZ:PROC	; CCmdTarget::OnCreateAggregates
EXTRN	?GetInterfaceHook@CCmdTarget@@UAEPAUIUnknown@@PBX@Z:PROC ; CCmdTarget::GetInterfaceHook
EXTRN	?GetExtraConnectionPoints@CCmdTarget@@MAEHPAVCPtrArray@@@Z:PROC ; CCmdTarget::GetExtraConnectionPoints
EXTRN	?GetConnectionHook@CCmdTarget@@MAEPAUIConnectionPoint@@ABU_GUID@@@Z:PROC ; CCmdTarget::GetConnectionHook
EXTRN	?PreSubclassWindow@CWnd@@UAEXXZ:PROC		; CWnd::PreSubclassWindow
EXTRN	?Create@CWnd@@UAEHPB_W0KABUtagRECT@@PAV1@IPAUCCreateContext@@@Z:PROC ; CWnd::Create
EXTRN	?CreateEx@CWnd@@UAEHKPB_W0KABUtagRECT@@PAV1@IPAX@Z:PROC ; CWnd::CreateEx
EXTRN	?CreateEx@CWnd@@UAEHKPB_W0KHHHHPAUHWND__@@PAUHMENU__@@PAX@Z:PROC ; CWnd::CreateEx
EXTRN	?DestroyWindow@CWnd@@UAEHXZ:PROC		; CWnd::DestroyWindow
EXTRN	?PreCreateWindow@CWnd@@UAEHAAUtagCREATESTRUCTW@@@Z:PROC ; CWnd::PreCreateWindow
EXTRN	?CalcWindowRect@CWnd@@UAEXPAUtagRECT@@I@Z:PROC	; CWnd::CalcWindowRect
EXTRN	?GetMenu@CWnd@@UBEPAVCMenu@@XZ:PROC		; CWnd::GetMenu
EXTRN	?SetMenu@CWnd@@UAEHPAVCMenu@@@Z:PROC		; CWnd::SetMenu
EXTRN	?OnToolHitTest@CWnd@@UBEHVCPoint@@PAUtagTOOLINFOW@@@Z:PROC ; CWnd::OnToolHitTest
EXTRN	?GetScrollBarCtrl@CWnd@@UBEPAVCScrollBar@@H@Z:PROC ; CWnd::GetScrollBarCtrl
EXTRN	?WinHelpW@CWnd@@UAEXKI@Z:PROC			; CWnd::WinHelpW
EXTRN	?HtmlHelpW@CWnd@@UAEXKI@Z:PROC			; CWnd::HtmlHelpW
EXTRN	?WinHelpInternal@CWnd@@UAEXKI@Z:PROC		; CWnd::WinHelpInternal
EXTRN	?ContinueModal@CWnd@@UAEHXZ:PROC		; CWnd::ContinueModal
EXTRN	?EndModalLoop@CWnd@@UAEXH@Z:PROC		; CWnd::EndModalLoop
EXTRN	?OnDrawIconicThumbnailOrLivePreview@CWnd@@UAEXAAVCDC@@VCRect@@VCSize@@HAAH@Z:PROC ; CWnd::OnDrawIconicThumbnailOrLivePreview
EXTRN	?EnsureStdObj@CWnd@@UAEJXZ:PROC			; CWnd::EnsureStdObj
EXTRN	?get_accParent@CWnd@@UAEJPAPAUIDispatch@@@Z:PROC ; CWnd::get_accParent
EXTRN	?get_accChildCount@CWnd@@UAEJPAJ@Z:PROC		; CWnd::get_accChildCount
EXTRN	?get_accChild@CWnd@@UAEJUtagVARIANT@@PAPAUIDispatch@@@Z:PROC ; CWnd::get_accChild
EXTRN	?get_accName@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accName
EXTRN	?get_accValue@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accValue
EXTRN	?get_accDescription@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accDescription
EXTRN	?get_accRole@CWnd@@UAEJUtagVARIANT@@PAU2@@Z:PROC ; CWnd::get_accRole
EXTRN	?get_accState@CWnd@@UAEJUtagVARIANT@@PAU2@@Z:PROC ; CWnd::get_accState
EXTRN	?get_accHelp@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accHelp
EXTRN	?get_accHelpTopic@CWnd@@UAEJPAPA_WUtagVARIANT@@PAJ@Z:PROC ; CWnd::get_accHelpTopic
EXTRN	?get_accKeyboardShortcut@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accKeyboardShortcut
EXTRN	?get_accFocus@CWnd@@UAEJPAUtagVARIANT@@@Z:PROC	; CWnd::get_accFocus
EXTRN	?get_accSelection@CWnd@@UAEJPAUtagVARIANT@@@Z:PROC ; CWnd::get_accSelection
EXTRN	?get_accDefaultAction@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z:PROC ; CWnd::get_accDefaultAction
EXTRN	?accSelect@CWnd@@UAEJJUtagVARIANT@@@Z:PROC	; CWnd::accSelect
EXTRN	?accLocation@CWnd@@UAEJPAJ000UtagVARIANT@@@Z:PROC ; CWnd::accLocation
EXTRN	?accNavigate@CWnd@@UAEJJUtagVARIANT@@PAU2@@Z:PROC ; CWnd::accNavigate
EXTRN	?accHitTest@CWnd@@UAEJJJPAUtagVARIANT@@@Z:PROC	; CWnd::accHitTest
EXTRN	?accDoDefaultAction@CWnd@@UAEJUtagVARIANT@@@Z:PROC ; CWnd::accDoDefaultAction
EXTRN	?put_accName@CWnd@@UAEJUtagVARIANT@@PA_W@Z:PROC	; CWnd::put_accName
EXTRN	?put_accValue@CWnd@@UAEJUtagVARIANT@@PA_W@Z:PROC ; CWnd::put_accValue
EXTRN	?SetProxy@CWnd@@UAEJPAUIAccessibleProxy@@@Z:PROC ; CWnd::SetProxy
EXTRN	?CreateAccessibleProxy@CWnd@@UAEJIJPAJ@Z:PROC	; CWnd::CreateAccessibleProxy
EXTRN	?OnCommand@CWnd@@MAEHIJ@Z:PROC			; CWnd::OnCommand
EXTRN	?OnNotify@CWnd@@MAEHIJPAJ@Z:PROC		; CWnd::OnNotify
EXTRN	?GetSuperWndProcAddr@CWnd@@MAEPAP6GJPAUHWND__@@IIJ@ZXZ:PROC ; CWnd::GetSuperWndProcAddr
EXTRN	?BeginModalState@CWnd@@UAEXXZ:PROC		; CWnd::BeginModalState
EXTRN	?EndModalState@CWnd@@UAEXXZ:PROC		; CWnd::EndModalState
EXTRN	?PreTranslateMessage@CDialog@@UAEHPAUtagMSG@@@Z:PROC ; CDialog::PreTranslateMessage
EXTRN	?OnAmbientProperty@CWnd@@UAEHPAVCOleControlSite@@JPAUtagVARIANT@@@Z:PROC ; CWnd::OnAmbientProperty
EXTRN	?WindowProc@CWnd@@MAEJIIJ@Z:PROC		; CWnd::WindowProc
EXTRN	?OnWndMsg@CWnd@@MAEHIIJPAJ@Z:PROC		; CWnd::OnWndMsg
EXTRN	?DefWindowProcW@CWnd@@MAEJIIJ@Z:PROC		; CWnd::DefWindowProcW
EXTRN	?PostNcDestroy@CWnd@@MAEXXZ:PROC		; CWnd::PostNcDestroy
EXTRN	?OnChildNotify@CWnd@@MAEHIIJPAJ@Z:PROC		; CWnd::OnChildNotify
EXTRN	?OnTouchInputs@CWnd@@MAEHIPAUtagTOUCHINPUT@@@Z:PROC ; CWnd::OnTouchInputs
EXTRN	?OnTouchInput@CWnd@@MAEHVCPoint@@HHPAUtagTOUCHINPUT@@@Z:PROC ; CWnd::OnTouchInput
EXTRN	?GetGestureStatus@CWnd@@MAEKVCPoint@@@Z:PROC	; CWnd::GetGestureStatus
EXTRN	?OnGestureZoom@CWnd@@MAEHVCPoint@@J@Z:PROC	; CWnd::OnGestureZoom
EXTRN	?OnGesturePan@CWnd@@MAEHVCPoint@@0@Z:PROC	; CWnd::OnGesturePan
EXTRN	?OnGestureRotate@CWnd@@MAEHVCPoint@@N@Z:PROC	; CWnd::OnGestureRotate
EXTRN	?OnGestureTwoFingerTap@CWnd@@MAEHVCPoint@@@Z:PROC ; CWnd::OnGestureTwoFingerTap
EXTRN	?OnGesturePressAndTap@CWnd@@MAEHVCPoint@@J@Z:PROC ; CWnd::OnGesturePressAndTap
EXTRN	?CheckAutoCenter@CDialog@@UAEHXZ:PROC		; CDialog::CheckAutoCenter
EXTRN	?IsFrameWnd@CWnd@@UBEHXZ:PROC			; CWnd::IsFrameWnd
EXTRN	?CreateControlContainer@CWnd@@MAEHPAPAVCOleControlContainer@@@Z:PROC ; CWnd::CreateControlContainer
EXTRN	?CreateControlSite@CWnd@@MAEHPAVCOleControlContainer@@PAPAVCOleControlSite@@IABU_GUID@@@Z:PROC ; CWnd::CreateControlSite
EXTRN	?SetOccDialogInfo@CDialog@@MAEHPAU_AFX_OCC_DIALOG_INFO@@@Z:PROC ; CDialog::SetOccDialogInfo
EXTRN	?GetOccDialogInfo@CDialog@@MAEPAU_AFX_OCC_DIALOG_INFO@@XZ:PROC ; CDialog::GetOccDialogInfo
EXTRN	?Create@CDialog@@UAEHIPAVCWnd@@@Z:PROC		; CDialog::Create
EXTRN	?Create@CDialog@@UAEHPB_WPAVCWnd@@@Z:PROC	; CDialog::Create
EXTRN	?CreateIndirect@CDialog@@UAEHPAXPAVCWnd@@@Z:PROC ; CDialog::CreateIndirect
EXTRN	?CreateIndirect@CDialog@@UAEHPBUDLGTEMPLATE@@PAVCWnd@@PAX@Z:PROC ; CDialog::CreateIndirect
EXTRN	?DoModal@CDialog@@UAEHXZ:PROC			; CDialog::DoModal
EXTRN	?OnSetFont@CDialog@@UAEXPAVCFont@@@Z:PROC	; CDialog::OnSetFont
EXTRN	?OnOK@CDialog@@MAEXXZ:PROC			; CDialog::OnOK
EXTRN	?OnCancel@CDialog@@MAEXXZ:PROC			; CDialog::OnCancel
EXTRN	?PreInitDialog@CDialog@@MAEXXZ:PROC		; CDialog::PreInitDialog
;	COMDAT ??_R2CObject@@8
; File d:\_code\rtfcontentctrl\inserttabledlg.cpp
rdata$r	SEGMENT
??_R2CObject@@8 DD FLAT:??_R1A@?0A@EA@CObject@@8	; CObject::`RTTI Base Class Array'
rdata$r	ENDS
;	COMDAT ??_R3CObject@@8
rdata$r	SEGMENT
??_R3CObject@@8 DD 00H					; CObject::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	01H
	DD	FLAT:??_R2CObject@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCObject@@@8
_DATA	SEGMENT
??_R0?AVCObject@@@8 DD FLAT:??_7type_info@@6B@		; CObject `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCObject@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@CObject@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CObject@@8 DD FLAT:??_R0?AVCObject@@@8	; CObject::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	00H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CObject@@8
rdata$r	ENDS
;	COMDAT ??_R2CCmdTarget@@8
rdata$r	SEGMENT
??_R2CCmdTarget@@8 DD FLAT:??_R1A@?0A@EA@CCmdTarget@@8	; CCmdTarget::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CCmdTarget@@8
rdata$r	SEGMENT
??_R3CCmdTarget@@8 DD 00H				; CCmdTarget::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	02H
	DD	FLAT:??_R2CCmdTarget@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCCmdTarget@@@8
_DATA	SEGMENT
??_R0?AVCCmdTarget@@@8 DD FLAT:??_7type_info@@6B@	; CCmdTarget `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCCmdTarget@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@CCmdTarget@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CCmdTarget@@8 DD FLAT:??_R0?AVCCmdTarget@@@8 ; CCmdTarget::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	01H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CCmdTarget@@8
rdata$r	ENDS
;	COMDAT ??_R2CWnd@@8
rdata$r	SEGMENT
??_R2CWnd@@8 DD	FLAT:??_R1A@?0A@EA@CWnd@@8		; CWnd::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CCmdTarget@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CWnd@@8
rdata$r	SEGMENT
??_R3CWnd@@8 DD	00H					; CWnd::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	03H
	DD	FLAT:??_R2CWnd@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCWnd@@@8
_DATA	SEGMENT
??_R0?AVCWnd@@@8 DD FLAT:??_7type_info@@6B@		; CWnd `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCWnd@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@CWnd@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CWnd@@8 DD FLAT:??_R0?AVCWnd@@@8		; CWnd::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	02H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CWnd@@8
rdata$r	ENDS
;	COMDAT ??_R2CDialog@@8
rdata$r	SEGMENT
??_R2CDialog@@8 DD FLAT:??_R1A@?0A@EA@CDialog@@8	; CDialog::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CWnd@@8
	DD	FLAT:??_R1A@?0A@EA@CCmdTarget@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CDialog@@8
rdata$r	SEGMENT
??_R3CDialog@@8 DD 00H					; CDialog::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	04H
	DD	FLAT:??_R2CDialog@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCDialog@@@8
_DATA	SEGMENT
??_R0?AVCDialog@@@8 DD FLAT:??_7type_info@@6B@		; CDialog `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCDialog@@', 00H
_DATA	ENDS
;	COMDAT ??_R1A@?0A@EA@CDialog@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CDialog@@8 DD FLAT:??_R0?AVCDialog@@@8	; CDialog::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	03H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CDialog@@8
rdata$r	ENDS
;	COMDAT ??_R1A@?0A@EA@CInsertTableDlg@@8
rdata$r	SEGMENT
??_R1A@?0A@EA@CInsertTableDlg@@8 DD FLAT:??_R0?AVCInsertTableDlg@@@8 ; CInsertTableDlg::`RTTI Base Class Descriptor at (0,-1,0,64)'
	DD	04H
	DD	00H
	DD	0ffffffffH
	DD	00H
	DD	040H
	DD	FLAT:??_R3CInsertTableDlg@@8
rdata$r	ENDS
;	COMDAT ??_R2CInsertTableDlg@@8
rdata$r	SEGMENT
??_R2CInsertTableDlg@@8 DD FLAT:??_R1A@?0A@EA@CInsertTableDlg@@8 ; CInsertTableDlg::`RTTI Base Class Array'
	DD	FLAT:??_R1A@?0A@EA@CDialog@@8
	DD	FLAT:??_R1A@?0A@EA@CWnd@@8
	DD	FLAT:??_R1A@?0A@EA@CCmdTarget@@8
	DD	FLAT:??_R1A@?0A@EA@CObject@@8
rdata$r	ENDS
;	COMDAT ??_R3CInsertTableDlg@@8
rdata$r	SEGMENT
??_R3CInsertTableDlg@@8 DD 00H				; CInsertTableDlg::`RTTI Class Hierarchy Descriptor'
	DD	00H
	DD	05H
	DD	FLAT:??_R2CInsertTableDlg@@8
rdata$r	ENDS
;	COMDAT ??_R0?AVCInsertTableDlg@@@8
_DATA	SEGMENT
??_R0?AVCInsertTableDlg@@@8 DD FLAT:??_7type_info@@6B@	; CInsertTableDlg `RTTI Type Descriptor'
	DD	00H
	DB	'.?AVCInsertTableDlg@@', 00H
_DATA	ENDS
;	COMDAT ??_R4CInsertTableDlg@@6B@
rdata$r	SEGMENT
??_R4CInsertTableDlg@@6B@ DD 00H			; CInsertTableDlg::`RTTI Complete Object Locator'
	DD	00H
	DD	00H
	DD	FLAT:??_R0?AVCInsertTableDlg@@@8
	DD	FLAT:??_R3CInsertTableDlg@@8
rdata$r	ENDS
;	COMDAT ??_7CInsertTableDlg@@6B@
CONST	SEGMENT
??_7CInsertTableDlg@@6B@ DD FLAT:??_R4CInsertTableDlg@@6B@ ; CInsertTableDlg::`vftable'
	DD	FLAT:?GetRuntimeClass@CDialog@@UBEPAUCRuntimeClass@@XZ
	DD	FLAT:??_ECInsertTableDlg@@UAEPAXI@Z
	DD	FLAT:?Serialize@CObject@@UAEXAAVCArchive@@@Z
	DD	FLAT:?AssertValid@CDialog@@UBEXXZ
	DD	FLAT:?Dump@CDialog@@UBEXAAVCDumpContext@@@Z
	DD	FLAT:?OnCmdMsg@CDialog@@UAEHIHPAXPAUAFX_CMDHANDLERINFO@@@Z
	DD	FLAT:?OnFinalRelease@CWnd@@UAEXXZ
	DD	FLAT:?IsInvokeAllowed@CCmdTarget@@UAEHJ@Z
	DD	FLAT:?GetDispatchIID@CCmdTarget@@UAEHPAU_GUID@@@Z
	DD	FLAT:?GetTypeInfoCount@CCmdTarget@@UAEIXZ
	DD	FLAT:?GetTypeLibCache@CCmdTarget@@UAEPAVCTypeLibCache@@XZ
	DD	FLAT:?GetTypeLib@CCmdTarget@@UAEJKPAPAUITypeLib@@@Z
	DD	FLAT:?GetMessageMap@CInsertTableDlg@@MBEPBUAFX_MSGMAP@@XZ
	DD	FLAT:?GetCommandMap@CCmdTarget@@MBEPBUAFX_OLECMDMAP@@XZ
	DD	FLAT:?GetDispatchMap@CCmdTarget@@MBEPBUAFX_DISPMAP@@XZ
	DD	FLAT:?GetConnectionMap@CCmdTarget@@MBEPBUAFX_CONNECTIONMAP@@XZ
	DD	FLAT:?GetInterfaceMap@CWnd@@MBEPBUAFX_INTERFACEMAP@@XZ
	DD	FLAT:?GetEventSinkMap@CCmdTarget@@MBEPBUAFX_EVENTSINKMAP@@XZ
	DD	FLAT:?OnCreateAggregates@CCmdTarget@@UAEHXZ
	DD	FLAT:?GetInterfaceHook@CCmdTarget@@UAEPAUIUnknown@@PBX@Z
	DD	FLAT:?GetExtraConnectionPoints@CCmdTarget@@MAEHPAVCPtrArray@@@Z
	DD	FLAT:?GetConnectionHook@CCmdTarget@@MAEPAUIConnectionPoint@@ABU_GUID@@@Z
	DD	FLAT:?PreSubclassWindow@CWnd@@UAEXXZ
	DD	FLAT:?Create@CWnd@@UAEHPB_W0KABUtagRECT@@PAV1@IPAUCCreateContext@@@Z
	DD	FLAT:?CreateEx@CWnd@@UAEHKPB_W0KABUtagRECT@@PAV1@IPAX@Z
	DD	FLAT:?CreateEx@CWnd@@UAEHKPB_W0KHHHHPAUHWND__@@PAUHMENU__@@PAX@Z
	DD	FLAT:?DestroyWindow@CWnd@@UAEHXZ
	DD	FLAT:?PreCreateWindow@CWnd@@UAEHAAUtagCREATESTRUCTW@@@Z
	DD	FLAT:?CalcWindowRect@CWnd@@UAEXPAUtagRECT@@I@Z
	DD	FLAT:?GetMenu@CWnd@@UBEPAVCMenu@@XZ
	DD	FLAT:?SetMenu@CWnd@@UAEHPAVCMenu@@@Z
	DD	FLAT:?OnToolHitTest@CWnd@@UBEHVCPoint@@PAUtagTOOLINFOW@@@Z
	DD	FLAT:?GetScrollBarCtrl@CWnd@@UBEPAVCScrollBar@@H@Z
	DD	FLAT:?WinHelpW@CWnd@@UAEXKI@Z
	DD	FLAT:?HtmlHelpW@CWnd@@UAEXKI@Z
	DD	FLAT:?WinHelpInternal@CWnd@@UAEXKI@Z
	DD	FLAT:?ContinueModal@CWnd@@UAEHXZ
	DD	FLAT:?EndModalLoop@CWnd@@UAEXH@Z
	DD	FLAT:?OnDrawIconicThumbnailOrLivePreview@CWnd@@UAEXAAVCDC@@VCRect@@VCSize@@HAAH@Z
	DD	FLAT:?EnsureStdObj@CWnd@@UAEJXZ
	DD	FLAT:?get_accParent@CWnd@@UAEJPAPAUIDispatch@@@Z
	DD	FLAT:?get_accChildCount@CWnd@@UAEJPAJ@Z
	DD	FLAT:?get_accChild@CWnd@@UAEJUtagVARIANT@@PAPAUIDispatch@@@Z
	DD	FLAT:?get_accName@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?get_accValue@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?get_accDescription@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?get_accRole@CWnd@@UAEJUtagVARIANT@@PAU2@@Z
	DD	FLAT:?get_accState@CWnd@@UAEJUtagVARIANT@@PAU2@@Z
	DD	FLAT:?get_accHelp@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?get_accHelpTopic@CWnd@@UAEJPAPA_WUtagVARIANT@@PAJ@Z
	DD	FLAT:?get_accKeyboardShortcut@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?get_accFocus@CWnd@@UAEJPAUtagVARIANT@@@Z
	DD	FLAT:?get_accSelection@CWnd@@UAEJPAUtagVARIANT@@@Z
	DD	FLAT:?get_accDefaultAction@CWnd@@UAEJUtagVARIANT@@PAPA_W@Z
	DD	FLAT:?accSelect@CWnd@@UAEJJUtagVARIANT@@@Z
	DD	FLAT:?accLocation@CWnd@@UAEJPAJ000UtagVARIANT@@@Z
	DD	FLAT:?accNavigate@CWnd@@UAEJJUtagVARIANT@@PAU2@@Z
	DD	FLAT:?accHitTest@CWnd@@UAEJJJPAUtagVARIANT@@@Z
	DD	FLAT:?accDoDefaultAction@CWnd@@UAEJUtagVARIANT@@@Z
	DD	FLAT:?put_accName@CWnd@@UAEJUtagVARIANT@@PA_W@Z
	DD	FLAT:?put_accValue@CWnd@@UAEJUtagVARIANT@@PA_W@Z
	DD	FLAT:?SetProxy@CWnd@@UAEJPAUIAccessibleProxy@@@Z
	DD	FLAT:?CreateAccessibleProxy@CWnd@@UAEJIJPAJ@Z
	DD	FLAT:?OnCommand@CWnd@@MAEHIJ@Z
	DD	FLAT:?OnNotify@CWnd@@MAEHIJPAJ@Z
	DD	FLAT:?GetSuperWndProcAddr@CWnd@@MAEPAP6GJPAUHWND__@@IIJ@ZXZ
	DD	FLAT:?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z
	DD	FLAT:?BeginModalState@CWnd@@UAEXXZ
	DD	FLAT:?EndModalState@CWnd@@UAEXXZ
	DD	FLAT:?PreTranslateMessage@CDialog@@UAEHPAUtagMSG@@@Z
	DD	FLAT:?OnAmbientProperty@CWnd@@UAEHPAVCOleControlSite@@JPAUtagVARIANT@@@Z
	DD	FLAT:?WindowProc@CWnd@@MAEJIIJ@Z
	DD	FLAT:?OnWndMsg@CWnd@@MAEHIIJPAJ@Z
	DD	FLAT:?DefWindowProcW@CWnd@@MAEJIIJ@Z
	DD	FLAT:?PostNcDestroy@CWnd@@MAEXXZ
	DD	FLAT:?OnChildNotify@CWnd@@MAEHIIJPAJ@Z
	DD	FLAT:?OnTouchInputs@CWnd@@MAEHIPAUtagTOUCHINPUT@@@Z
	DD	FLAT:?OnTouchInput@CWnd@@MAEHVCPoint@@HHPAUtagTOUCHINPUT@@@Z
	DD	FLAT:?GetGestureStatus@CWnd@@MAEKVCPoint@@@Z
	DD	FLAT:?OnGestureZoom@CWnd@@MAEHVCPoint@@J@Z
	DD	FLAT:?OnGesturePan@CWnd@@MAEHVCPoint@@0@Z
	DD	FLAT:?OnGestureRotate@CWnd@@MAEHVCPoint@@N@Z
	DD	FLAT:?OnGestureTwoFingerTap@CWnd@@MAEHVCPoint@@@Z
	DD	FLAT:?OnGesturePressAndTap@CWnd@@MAEHVCPoint@@J@Z
	DD	FLAT:?CheckAutoCenter@CDialog@@UAEHXZ
	DD	FLAT:?IsFrameWnd@CWnd@@UBEHXZ
	DD	FLAT:?CreateControlContainer@CWnd@@MAEHPAPAVCOleControlContainer@@@Z
	DD	FLAT:?CreateControlSite@CWnd@@MAEHPAVCOleControlContainer@@PAPAVCOleControlSite@@IABU_GUID@@@Z
	DD	FLAT:?SetOccDialogInfo@CDialog@@MAEHPAU_AFX_OCC_DIALOG_INFO@@@Z
	DD	FLAT:?GetOccDialogInfo@CDialog@@MAEPAU_AFX_OCC_DIALOG_INFO@@XZ
	DD	FLAT:?Create@CDialog@@UAEHIPAVCWnd@@@Z
	DD	FLAT:?Create@CDialog@@UAEHPB_WPAVCWnd@@@Z
	DD	FLAT:?CreateIndirect@CDialog@@UAEHPAXPAVCWnd@@@Z
	DD	FLAT:?CreateIndirect@CDialog@@UAEHPBUDLGTEMPLATE@@PAVCWnd@@PAX@Z
	DD	FLAT:?DoModal@CDialog@@UAEHXZ
	DD	FLAT:?OnInitDialog@CInsertTableDlg@@MAEHXZ
	DD	FLAT:?OnSetFont@CDialog@@UAEXPAVCFont@@@Z
	DD	FLAT:?OnOK@CDialog@@MAEXXZ
	DD	FLAT:?OnCancel@CDialog@@MAEXXZ
	DD	FLAT:?PreInitDialog@CDialog@@MAEXXZ
CONST	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z$0
	DD	00H
	DD	FLAT:__unwindfunclet$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z$1
	DD	01H
	DD	FLAT:__unwindfunclet$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z$2
__ehfuncinfo$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z DD 019930522H
	DD	03H
	DD	FLAT:__unwindtable$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
xdata$x	ENDS
;	COMDAT rtc$TMZ
rtc$TMZ	SEGMENT
__RTC_Shutdown.rtc$TMZ DD FLAT:__RTC_Shutdown
rtc$TMZ	ENDS
;	COMDAT rtc$IMZ
rtc$IMZ	SEGMENT
__RTC_InitBase.rtc$IMZ DD FLAT:__RTC_InitBase
; Function compile flags: /Odtp /RTCsu
rtc$IMZ	ENDS
;	COMDAT ??0CInsertTableDlg@@QAE@PAVCWnd@@@Z
_TEXT	SEGMENT
_this$ = -16						; size = 4
__$EHRec$ = -12						; size = 12
_pParent$ = 8						; size = 4
??0CInsertTableDlg@@QAE@PAVCWnd@@@Z PROC		; CInsertTableDlg::CInsertTableDlg, COMDAT
; _this$ = ecx

; 21   : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	push	ecx
	mov	DWORD PTR [ebp-16], -858993460		; ccccccccH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	eax, DWORD PTR _pParent$[ebp]
	push	eax
	push	16006					; 00003e86H
	mov	ecx, DWORD PTR _this$[ebp]
	call	??0CDialog@@QAE@IPAVCWnd@@@Z		; CDialog::CDialog
	mov	DWORD PTR __$EHRec$[ebp+8], 0
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx], OFFSET ??_7CInsertTableDlg@@6B@
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 148				; 00000094H
	call	??0CComboBox@@QAE@XZ			; CComboBox::CComboBox
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 264				; 00000108H
	call	??0CComboBox@@QAE@XZ			; CComboBox::CComboBox
	mov	BYTE PTR __$EHRec$[ebp+8], 2
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 380				; 0000017cH
	call	??0CComboBox@@QAE@XZ			; CComboBox::CComboBox
	mov	edx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [edx+496], 4
	mov	eax, DWORD PTR _this$[ebp]
	mov	DWORD PTR [eax+500], 4
	mov	ecx, DWORD PTR _this$[ebp]
	mov	DWORD PTR [ecx+504], 3

; 22   : 	//{{AFX_DATA_INIT(CInsertTableDlg)
; 23   : 	//}}AFX_DATA_INIT
; 24   : // 	m_nPadLeft = 0;
; 25   : // 	m_nPadTop = 0;
; 26   : // 	m_nPadRight = 0;
; 27   : // 	m_nPadBottom = 0;
; 28   : }

	mov	DWORD PTR __$EHRec$[ebp+8], -1
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	add	esp, 16					; 00000010H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z$0:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	??1CDialog@@UAE@XZ			; CDialog::~CDialog
__unwindfunclet$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z$1:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 148				; 00000094H
	jmp	??1CComboBox@@UAE@XZ			; CComboBox::~CComboBox
__unwindfunclet$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z$2:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 264				; 00000108H
	jmp	??1CComboBox@@UAE@XZ			; CComboBox::~CComboBox
__ehhandler$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-8]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??0CInsertTableDlg@@QAE@PAVCWnd@@@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
??0CInsertTableDlg@@QAE@PAVCWnd@@@Z ENDP		; CInsertTableDlg::CInsertTableDlg
PUBLIC	??1CInsertTableDlg@@UAE@XZ			; CInsertTableDlg::~CInsertTableDlg
EXTRN	??3CObject@@SGXPAX@Z:PROC			; CObject::operator delete
; Function compile flags: /Odtp /RTCsu
;	COMDAT ??_GCInsertTableDlg@@UAEPAXI@Z
_TEXT	SEGMENT
_this$ = -4						; size = 4
___flags$ = 8						; size = 4
??_GCInsertTableDlg@@UAEPAXI@Z PROC			; CInsertTableDlg::`scalar deleting destructor', COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CInsertTableDlg@@UAE@XZ
	mov	eax, DWORD PTR ___flags$[ebp]
	and	eax, 1
	je	SHORT $LN1@scalar
	mov	ecx, DWORD PTR _this$[ebp]
	push	ecx
	call	??3CObject@@SGXPAX@Z			; CObject::operator delete
$LN1@scalar:
	mov	eax, DWORD PTR _this$[ebp]
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
??_GCInsertTableDlg@@UAEPAXI@Z ENDP			; CInsertTableDlg::`scalar deleting destructor'
_TEXT	ENDS
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$??1CInsertTableDlg@@UAE@XZ DD 0ffffffffH
	DD	FLAT:__unwindfunclet$??1CInsertTableDlg@@UAE@XZ$0
	DD	00H
	DD	FLAT:__unwindfunclet$??1CInsertTableDlg@@UAE@XZ$1
	DD	01H
	DD	FLAT:__unwindfunclet$??1CInsertTableDlg@@UAE@XZ$2
__ehfuncinfo$??1CInsertTableDlg@@UAE@XZ DD 019930522H
	DD	03H
	DD	FLAT:__unwindtable$??1CInsertTableDlg@@UAE@XZ
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Odtp /RTCsu
xdata$x	ENDS
;	COMDAT ??1CInsertTableDlg@@UAE@XZ
_TEXT	SEGMENT
_this$ = -16						; size = 4
__$EHRec$ = -12						; size = 12
??1CInsertTableDlg@@UAE@XZ PROC				; CInsertTableDlg::~CInsertTableDlg, COMDAT
; _this$ = ecx
	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$??1CInsertTableDlg@@UAE@XZ
	mov	eax, DWORD PTR fs:0
	push	eax
	push	ecx
	mov	DWORD PTR [ebp-16], -858993460		; ccccccccH
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx
	mov	DWORD PTR __$EHRec$[ebp+8], 2
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 380				; 0000017cH
	call	??1CComboBox@@UAE@XZ			; CComboBox::~CComboBox
	mov	BYTE PTR __$EHRec$[ebp+8], 1
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 264				; 00000108H
	call	??1CComboBox@@UAE@XZ			; CComboBox::~CComboBox
	mov	BYTE PTR __$EHRec$[ebp+8], 0
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 148				; 00000094H
	call	??1CComboBox@@UAE@XZ			; CComboBox::~CComboBox
	mov	DWORD PTR __$EHRec$[ebp+8], -1
	mov	ecx, DWORD PTR _this$[ebp]
	call	??1CDialog@@UAE@XZ			; CDialog::~CDialog
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	add	esp, 16					; 00000010H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$??1CInsertTableDlg@@UAE@XZ$0:
	mov	ecx, DWORD PTR _this$[ebp]
	jmp	??1CDialog@@UAE@XZ			; CDialog::~CDialog
__unwindfunclet$??1CInsertTableDlg@@UAE@XZ$1:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 148				; 00000094H
	jmp	??1CComboBox@@UAE@XZ			; CComboBox::~CComboBox
__unwindfunclet$??1CInsertTableDlg@@UAE@XZ$2:
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 264				; 00000108H
	jmp	??1CComboBox@@UAE@XZ			; CComboBox::~CComboBox
__ehhandler$??1CInsertTableDlg@@UAE@XZ:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-8]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$??1CInsertTableDlg@@UAE@XZ
	jmp	___CxxFrameHandler3
text$x	ENDS
??1CInsertTableDlg@@UAE@XZ ENDP				; CInsertTableDlg::~CInsertTableDlg
EXTRN	?SelectString@CComboBox@@QAEHHPB_W@Z:PROC	; CComboBox::SelectString
EXTRN	__imp_?Format@?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAAXPB_WZZ:PROC
EXTRN	__imp_??1?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ:PROC
EXTRN	__imp___wtoi:PROC
EXTRN	__imp_??B?$CSimpleStringT@_W$00@ATL@@QBEPB_WXZ:PROC
EXTRN	?GetWindowTextW@CWnd@@QBEXAAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z:PROC ; CWnd::GetWindowTextW
EXTRN	?GetDlgItem@CWnd@@QBEPAV1@H@Z:PROC		; CWnd::GetDlgItem
EXTRN	__imp_??0?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ:PROC
EXTRN	?DDX_Control@@YGXPAVCDataExchange@@HAAVCWnd@@@Z:PROC ; DDX_Control
EXTRN	?DoDataExchange@CWnd@@MAEXPAVCDataExchange@@@Z:PROC ; CWnd::DoDataExchange
EXTRN	@_RTC_CheckStackVars@8:PROC
;	COMDAT xdata$x
xdata$x	SEGMENT
__unwindtable$?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z DD 0ffffffffH
	DD	FLAT:__unwindfunclet$?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z$0
	DD	0ffffffffH
	DD	FLAT:__unwindfunclet$?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z$1
__ehfuncinfo$?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z DD 019930522H
	DD	02H
	DD	FLAT:__unwindtable$?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z
	DD	2 DUP(00H)
	DD	2 DUP(00H)
	DD	00H
	DD	01H
; Function compile flags: /Odtp /RTCsu
xdata$x	ENDS
;	COMDAT ?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z
_TEXT	SEGMENT
tv213 = -52						; size = 4
tv185 = -48						; size = 4
tv157 = -44						; size = 4
_sValue$171448 = -36					; size = 4
_sValue$171446 = -24					; size = 4
_this$ = -16						; size = 4
__$EHRec$ = -12						; size = 12
_pDX$ = 8						; size = 4
?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z PROC ; CInsertTableDlg::DoDataExchange, COMDAT
; _this$ = ecx

; 32   : {

	push	ebp
	mov	ebp, esp
	push	-1
	push	__ehhandler$?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z
	mov	eax, DWORD PTR fs:0
	push	eax
	sub	esp, 40					; 00000028H
	push	esi
	push	edi
	push	ecx
	lea	edi, DWORD PTR [ebp-52]
	mov	ecx, 10					; 0000000aH
	mov	eax, -858993460				; ccccccccH
	rep stosd
	pop	ecx
	mov	eax, DWORD PTR ___security_cookie
	xor	eax, ebp
	push	eax
	lea	eax, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, eax
	mov	DWORD PTR _this$[ebp], ecx

; 33   : 	CDialog::DoDataExchange(pDX);

	mov	eax, DWORD PTR _pDX$[ebp]
	push	eax
	mov	ecx, DWORD PTR _this$[ebp]
	call	?DoDataExchange@CWnd@@MAEXPAVCDataExchange@@@Z ; CWnd::DoDataExchange

; 34   : 	//{{AFX_DATA_MAP(CInsertTableDlg)
; 35   : 	DDX_Control(pDX, IDC_COLWIDTH, m_cbColWidth);

	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 148				; 00000094H
	push	ecx
	push	16010					; 00003e8aH
	mov	edx, DWORD PTR _pDX$[ebp]
	push	edx
	call	?DDX_Control@@YGXPAVCDataExchange@@HAAVCWnd@@@Z ; DDX_Control

; 36   : 	DDX_Control(pDX, IDC_NUMCOLS, m_cbCols);

	mov	eax, DWORD PTR _this$[ebp]
	add	eax, 264				; 00000108H
	push	eax
	push	16009					; 00003e89H
	mov	ecx, DWORD PTR _pDX$[ebp]
	push	ecx
	call	?DDX_Control@@YGXPAVCDataExchange@@HAAVCWnd@@@Z ; DDX_Control

; 37   : 	DDX_Control(pDX, IDC_NUMROWS, m_cbRows);

	mov	edx, DWORD PTR _this$[ebp]
	add	edx, 380				; 0000017cH
	push	edx
	push	16008					; 00003e88H
	mov	eax, DWORD PTR _pDX$[ebp]
	push	eax
	call	?DDX_Control@@YGXPAVCDataExchange@@HAAVCWnd@@@Z ; DDX_Control

; 38   : 	//}}AFX_DATA_MAP
; 39   : // 	DDX_Text(pDX, IDC_PADLEFT, m_nPadLeft);
; 40   : // 	DDX_Text(pDX, IDC_PADTOP, m_nPadTop);
; 41   : // 	DDX_Text(pDX, IDC_PADRIGHT, m_nPadRight);
; 42   : // 	DDX_Text(pDX, IDC_PADBOTTOM, m_nPadBottom);
; 43   : 
; 44   : 	if (pDX->m_bSaveAndValidate)

	mov	ecx, DWORD PTR _pDX$[ebp]
	cmp	DWORD PTR [ecx], 0
	je	$LN2@DoDataExch

; 45   : 	{
; 46   : 		CString sValue;

	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171446[ebp]
	call	DWORD PTR __imp_??0?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR __$EHRec$[ebp+8], 0

; 47   : 
; 48   : 		GetDlgItem(IDC_NUMCOLS)->GetWindowText(sValue);

	lea	edx, DWORD PTR _sValue$171446[ebp]
	push	edx
	push	16009					; 00003e89H
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?GetWindowTextW@CWnd@@QBEXAAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z ; CWnd::GetWindowTextW

; 49   : 		m_nNumCols = max(_ttoi(sValue), 1);

	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171446[ebp]
	call	DWORD PTR __imp_??B?$CSimpleStringT@_W$00@ATL@@QBEPB_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	call	DWORD PTR __imp___wtoi
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	cmp	eax, 1
	jle	SHORT $LN5@DoDataExch
	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171446[ebp]
	call	DWORD PTR __imp_??B?$CSimpleStringT@_W$00@ATL@@QBEPB_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	call	DWORD PTR __imp___wtoi
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR tv157[ebp], eax
	jmp	SHORT $LN6@DoDataExch
$LN5@DoDataExch:
	mov	DWORD PTR tv157[ebp], 1
$LN6@DoDataExch:
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR tv157[ebp]
	mov	DWORD PTR [eax+500], ecx

; 50   : 
; 51   : 		GetDlgItem(IDC_NUMROWS)->GetWindowText(sValue);

	lea	edx, DWORD PTR _sValue$171446[ebp]
	push	edx
	push	16008					; 00003e88H
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?GetWindowTextW@CWnd@@QBEXAAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z ; CWnd::GetWindowTextW

; 52   : 		m_nNumRows = max(_ttoi(sValue), 1);

	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171446[ebp]
	call	DWORD PTR __imp_??B?$CSimpleStringT@_W$00@ATL@@QBEPB_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	call	DWORD PTR __imp___wtoi
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	cmp	eax, 1
	jle	SHORT $LN7@DoDataExch
	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171446[ebp]
	call	DWORD PTR __imp_??B?$CSimpleStringT@_W$00@ATL@@QBEPB_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	call	DWORD PTR __imp___wtoi
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR tv185[ebp], eax
	jmp	SHORT $LN8@DoDataExch
$LN7@DoDataExch:
	mov	DWORD PTR tv185[ebp], 1
$LN8@DoDataExch:
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR tv185[ebp]
	mov	DWORD PTR [eax+496], ecx

; 53   : 
; 54   : 		GetDlgItem(IDC_COLWIDTH)->GetWindowText(sValue);

	lea	edx, DWORD PTR _sValue$171446[ebp]
	push	edx
	push	16010					; 00003e8aH
	mov	ecx, DWORD PTR _this$[ebp]
	call	?GetDlgItem@CWnd@@QBEPAV1@H@Z		; CWnd::GetDlgItem
	mov	ecx, eax
	call	?GetWindowTextW@CWnd@@QBEXAAV?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@@Z ; CWnd::GetWindowTextW

; 55   : 		m_nColWidth = max(_ttoi(sValue), 1);

	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171446[ebp]
	call	DWORD PTR __imp_??B?$CSimpleStringT@_W$00@ATL@@QBEPB_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	call	DWORD PTR __imp___wtoi
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	cmp	eax, 1
	jle	SHORT $LN9@DoDataExch
	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171446[ebp]
	call	DWORD PTR __imp_??B?$CSimpleStringT@_W$00@ATL@@QBEPB_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	esi, esp
	push	eax
	call	DWORD PTR __imp___wtoi
	add	esp, 4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR tv213[ebp], eax
	jmp	SHORT $LN10@DoDataExch
$LN9@DoDataExch:
	mov	DWORD PTR tv213[ebp], 1
$LN10@DoDataExch:
	mov	eax, DWORD PTR _this$[ebp]
	mov	ecx, DWORD PTR tv213[ebp]
	mov	DWORD PTR [eax+504], ecx

; 56   : 	}

	mov	DWORD PTR __$EHRec$[ebp+8], -1
	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171446[ebp]
	call	DWORD PTR __imp_??1?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ
	cmp	esi, esp
	call	__RTC_CheckEsp

; 57   : 	else

	jmp	$LN3@DoDataExch
$LN2@DoDataExch:

; 58   : 	{
; 59   : 		CString sValue;

	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171448[ebp]
	call	DWORD PTR __imp_??0?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR __$EHRec$[ebp+8], 1

; 60   : 
; 61   : 		sValue.Format(_T("%d"), m_nNumCols);

	mov	esi, esp
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+500]
	push	eax
	push	OFFSET $SG171449
	lea	ecx, DWORD PTR _sValue$171448[ebp]
	push	ecx
	call	DWORD PTR __imp_?Format@?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAAXPB_WZZ
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp

; 62   : 		m_cbCols.SelectString(-1, sValue);

	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171448[ebp]
	call	DWORD PTR __imp_??B?$CSimpleStringT@_W$00@ATL@@QBEPB_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	push	eax
	push	-1
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 264				; 00000108H
	call	?SelectString@CComboBox@@QAEHHPB_W@Z	; CComboBox::SelectString

; 63   : 		
; 64   : 		sValue.Format(_T("%d"), m_nNumRows);

	mov	esi, esp
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+496]
	push	eax
	push	OFFSET $SG171450
	lea	ecx, DWORD PTR _sValue$171448[ebp]
	push	ecx
	call	DWORD PTR __imp_?Format@?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAAXPB_WZZ
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp

; 65   : 		m_cbRows.SelectString(-1, sValue);

	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171448[ebp]
	call	DWORD PTR __imp_??B?$CSimpleStringT@_W$00@ATL@@QBEPB_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	push	eax
	push	-1
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 380				; 0000017cH
	call	?SelectString@CComboBox@@QAEHHPB_W@Z	; CComboBox::SelectString

; 66   : 		
; 67   : 		sValue.Format(_T("%d"), m_nColWidth);

	mov	esi, esp
	mov	edx, DWORD PTR _this$[ebp]
	mov	eax, DWORD PTR [edx+504]
	push	eax
	push	OFFSET $SG171451
	lea	ecx, DWORD PTR _sValue$171448[ebp]
	push	ecx
	call	DWORD PTR __imp_?Format@?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAAXPB_WZZ
	add	esp, 12					; 0000000cH
	cmp	esi, esp
	call	__RTC_CheckEsp

; 68   : 		m_cbColWidth.SelectString(-1, sValue);

	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171448[ebp]
	call	DWORD PTR __imp_??B?$CSimpleStringT@_W$00@ATL@@QBEPB_WXZ
	cmp	esi, esp
	call	__RTC_CheckEsp
	push	eax
	push	-1
	mov	ecx, DWORD PTR _this$[ebp]
	add	ecx, 148				; 00000094H
	call	?SelectString@CComboBox@@QAEHHPB_W@Z	; CComboBox::SelectString

; 69   : 	}

	mov	DWORD PTR __$EHRec$[ebp+8], -1
	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171448[ebp]
	call	DWORD PTR __imp_??1?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ
	cmp	esi, esp
	call	__RTC_CheckEsp
$LN3@DoDataExch:

; 70   : }

	push	edx
	mov	ecx, ebp
	push	eax
	lea	edx, DWORD PTR $LN17@DoDataExch
	call	@_RTC_CheckStackVars@8
	pop	eax
	pop	edx
	mov	ecx, DWORD PTR __$EHRec$[ebp]
	mov	DWORD PTR fs:0, ecx
	pop	ecx
	pop	edi
	pop	esi
	add	esp, 52					; 00000034H
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	4
	npad	2
$LN17@DoDataExch:
	DD	2
	DD	$LN16@DoDataExch
$LN16@DoDataExch:
	DD	-24					; ffffffe8H
	DD	4
	DD	$LN13@DoDataExch
	DD	-36					; ffffffdcH
	DD	4
	DD	$LN14@DoDataExch
$LN14@DoDataExch:
	DB	115					; 00000073H
	DB	86					; 00000056H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	117					; 00000075H
	DB	101					; 00000065H
	DB	0
$LN13@DoDataExch:
	DB	115					; 00000073H
	DB	86					; 00000056H
	DB	97					; 00000061H
	DB	108					; 0000006cH
	DB	117					; 00000075H
	DB	101					; 00000065H
	DB	0
_TEXT	ENDS
;	COMDAT text$x
text$x	SEGMENT
__unwindfunclet$?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z$0:
	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171446[ebp]
	call	DWORD PTR __imp_??1?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ
	cmp	esi, esp
	jmp	__RTC_CheckEsp
__unwindfunclet$?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z$1:
	mov	esi, esp
	lea	ecx, DWORD PTR _sValue$171448[ebp]
	call	DWORD PTR __imp_??1?$CStringT@_WV?$StrTraitMFC_DLL@_WV?$ChTraitsCRT@_W@ATL@@@@@ATL@@QAE@XZ
	cmp	esi, esp
	jmp	__RTC_CheckEsp
__ehhandler$?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z:
	mov	edx, DWORD PTR [esp+8]
	lea	eax, DWORD PTR [edx+12]
	mov	ecx, DWORD PTR [edx-52]
	xor	ecx, eax
	call	@__security_check_cookie@4
	mov	eax, OFFSET __ehfuncinfo$?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z
	jmp	___CxxFrameHandler3
text$x	ENDS
?DoDataExchange@CInsertTableDlg@@MAEXPAVCDataExchange@@@Z ENDP ; CInsertTableDlg::DoDataExchange
PUBLIC	?GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ ; CInsertTableDlg::GetThisMessageMap
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?GetMessageMap@CInsertTableDlg@@MBEPBUAFX_MSGMAP@@XZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?GetMessageMap@CInsertTableDlg@@MBEPBUAFX_MSGMAP@@XZ PROC ; CInsertTableDlg::GetMessageMap, COMDAT
; _this$ = ecx

; 73   : BEGIN_MESSAGE_MAP(CInsertTableDlg, CDialog)

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx
	call	?GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ ; CInsertTableDlg::GetThisMessageMap
	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?GetMessageMap@CInsertTableDlg@@MBEPBUAFX_MSGMAP@@XZ ENDP ; CInsertTableDlg::GetMessageMap
_TEXT	ENDS
EXTRN	?GetThisMessageMap@CDialog@@KGPBUAFX_MSGMAP@@XZ:PROC ; CDialog::GetThisMessageMap
;	COMDAT ?_messageEntries@?1??GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ@4QBUAFX_MSGMAP_ENTRY@@B
CONST	SEGMENT
?_messageEntries@?1??GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ@4QBUAFX_MSGMAP_ENTRY@@B DD 00H ; `CInsertTableDlg::GetThisMessageMap'::`2'::_messageEntries
	DD	00H
	DD	00H
	DD	00H
	DD	00H
	DD	00H
CONST	ENDS
;	COMDAT ?messageMap@?1??GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ@4U3@B
CONST	SEGMENT
?messageMap@?1??GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ@4U3@B DD FLAT:?GetThisMessageMap@CDialog@@KGPBUAFX_MSGMAP@@XZ ; `CInsertTableDlg::GetThisMessageMap'::`2'::messageMap
	DD	FLAT:?_messageEntries@?1??GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ@4QBUAFX_MSGMAP_ENTRY@@B
; Function compile flags: /Odtp /RTCsu
CONST	ENDS
;	COMDAT ?GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ
_TEXT	SEGMENT
?GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ PROC ; CInsertTableDlg::GetThisMessageMap, COMDAT

; 73   : BEGIN_MESSAGE_MAP(CInsertTableDlg, CDialog)

	push	ebp
	mov	ebp, esp

; 74   : 	//{{AFX_MSG_MAP(CInsertTableDlg)
; 75   : 	//}}AFX_MSG_MAP
; 76   : END_MESSAGE_MAP()

	mov	eax, OFFSET ?messageMap@?1??GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ@4U3@B
	pop	ebp
	ret	0
?GetThisMessageMap@CInsertTableDlg@@KGPBUAFX_MSGMAP@@XZ ENDP ; CInsertTableDlg::GetThisMessageMap
_TEXT	ENDS
EXTRN	?OnInitDialog@CDialog@@UAEHXZ:PROC		; CDialog::OnInitDialog
; Function compile flags: /Odtp /RTCsu
;	COMDAT ?OnInitDialog@CInsertTableDlg@@MAEHXZ
_TEXT	SEGMENT
_this$ = -4						; size = 4
?OnInitDialog@CInsertTableDlg@@MAEHXZ PROC		; CInsertTableDlg::OnInitDialog, COMDAT
; _this$ = ecx

; 82   : {

	push	ebp
	mov	ebp, esp
	push	ecx
	mov	DWORD PTR [ebp-4], -858993460		; ccccccccH
	mov	DWORD PTR _this$[ebp], ecx

; 83   : 	CDialog::OnInitDialog();

	mov	ecx, DWORD PTR _this$[ebp]
	call	?OnInitDialog@CDialog@@UAEHXZ		; CDialog::OnInitDialog

; 84   : 	
; 85   : 	// TODO: Add extra initialization here
; 86   : 	
; 87   : 	return TRUE;  // return TRUE unless you set the focus to a control

	mov	eax, 1

; 88   : 	              // EXCEPTION: OCX Property Pages should return FALSE
; 89   : }

	add	esp, 4
	cmp	ebp, esp
	call	__RTC_CheckEsp
	mov	esp, ebp
	pop	ebp
	ret	0
?OnInitDialog@CInsertTableDlg@@MAEHXZ ENDP		; CInsertTableDlg::OnInitDialog
_TEXT	ENDS
EXTRN	__imp__RegisterWindowMessageW@4:PROC
; Function compile flags: /Odtp /RTCsu
; File d:\_code\interfaces\icontentcontrol.h
;	COMDAT ??__EWM_ICC_WANTSPELLCHECK@@YAXXZ
text$yc	SEGMENT
??__EWM_ICC_WANTSPELLCHECK@@YAXXZ PROC			; `dynamic initializer for 'WM_ICC_WANTSPELLCHECK'', COMDAT

; 25   : const UINT WM_ICC_WANTSPELLCHECK 	= ::RegisterWindowMessageW(L"WM_ICC_WANTSPELLCHECK");

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, esp
	push	OFFSET $SG171208
	call	DWORD PTR __imp__RegisterWindowMessageW@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _WM_ICC_WANTSPELLCHECK, eax
	pop	esi
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
??__EWM_ICC_WANTSPELLCHECK@@YAXXZ ENDP			; `dynamic initializer for 'WM_ICC_WANTSPELLCHECK''
; Function compile flags: /Odtp /RTCsu
text$yc	ENDS
;	COMDAT ??__EWM_ICC_COMMENTSCHANGE@@YAXXZ
text$yc	SEGMENT
??__EWM_ICC_COMMENTSCHANGE@@YAXXZ PROC			; `dynamic initializer for 'WM_ICC_COMMENTSCHANGE'', COMDAT

; 26   : const UINT WM_ICC_COMMENTSCHANGE	= ::RegisterWindowMessageW(L"WM_ICC_COMMENTSCHANGE");

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, esp
	push	OFFSET $SG171213
	call	DWORD PTR __imp__RegisterWindowMessageW@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _WM_ICC_COMMENTSCHANGE, eax
	pop	esi
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
??__EWM_ICC_COMMENTSCHANGE@@YAXXZ ENDP			; `dynamic initializer for 'WM_ICC_COMMENTSCHANGE''
; Function compile flags: /Odtp /RTCsu
text$yc	ENDS
;	COMDAT ??__EWM_ICC_COMMENTSKILLFOCUS@@YAXXZ
text$yc	SEGMENT
??__EWM_ICC_COMMENTSKILLFOCUS@@YAXXZ PROC		; `dynamic initializer for 'WM_ICC_COMMENTSKILLFOCUS'', COMDAT

; 27   : const UINT WM_ICC_COMMENTSKILLFOCUS	= ::RegisterWindowMessageW(L"WM_ICC_COMMENTSKILLFOCUS");

	push	ebp
	mov	ebp, esp
	push	esi
	mov	esi, esp
	push	OFFSET $SG171218
	call	DWORD PTR __imp__RegisterWindowMessageW@4
	cmp	esi, esp
	call	__RTC_CheckEsp
	mov	DWORD PTR _WM_ICC_COMMENTSKILLFOCUS, eax
	pop	esi
	cmp	ebp, esp
	call	__RTC_CheckEsp
	pop	ebp
	ret	0
??__EWM_ICC_COMMENTSKILLFOCUS@@YAXXZ ENDP		; `dynamic initializer for 'WM_ICC_COMMENTSKILLFOCUS''
text$yc	ENDS
_BSS	SEGMENT
_WM_ICC_COMMENTSKILLFOCUS DD 01H DUP (?)
_WM_ICC_COMMENTSCHANGE DD 01H DUP (?)
_WM_ICC_WANTSPELLCHECK DD 01H DUP (?)
_BSS	ENDS
CRT$XCU	SEGMENT
_WM_ICC_WANTSPELLCHECK$initializer$ DD FLAT:??__EWM_ICC_WANTSPELLCHECK@@YAXXZ
_WM_ICC_COMMENTSCHANGE$initializer$ DD FLAT:??__EWM_ICC_COMMENTSCHANGE@@YAXXZ
_WM_ICC_COMMENTSKILLFOCUS$initializer$ DD FLAT:??__EWM_ICC_COMMENTSKILLFOCUS@@YAXXZ
CRT$XCU	ENDS
END
